# Makefile for my GLES-based library: Glesly
#

NAME                 =  Glesly_Earth
VERS_MAJOR           =  0
VERS_MINOR           =  1

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

SHADER_PATH          =  $(PWD)/shaders

include $(SCRIPTDIR)/makelib
include $(GLSCRIPTS)/shader.rules

